import { Globals } from '../../constants';
/*
 https://ywait.in:2003 --> Staging
 https://y-wait.com:2001 --> QA
 https://y-wait.com:5002 --> Development
 https://ywait.org:8881 --> Prod
 https://y-wait.com:5010--> Insta Staging 
*/
export default {
  BASE_URL: 'https://ywait.org:8881',
  URL_TYPE: 'Prod',
  DEV_URL: 'https://y-wait.com:5002',
  QA_URL: 'https://y-wait.com:2001',
  STAGE_URL: 'https://ywait.in:2003',
  PROD_URL: 'https://ywait.org:8881',
  DEFAULT_URL: 'https://ywait.org:8881',

  ENDPOINTS: {
    BUSINESS_LIST: '/app/admin/list/business',
    BUSINESS_DETAILS: '/app/admin/details/business',
    EMAIL_LOGIN: '/app/admin/email/login',
    PHONE_LOGIN: '/app/admin/signin',
    PIN_VERIFY: '/app/admin/verify/user-pin',
    UPDATE_AUTH_PIN_SETTINGS: '/app/admin/enable/pin/authentication',
    UPDATE_USER_PIN: '/app/admin/update/user-pin',
    FORGOT_PASSWORD: '/app/admin/forgot/password',
    PASSWORD_RESET: '/app/admin/update/new-user',
    FORGOT_PIN_EMAIL: '/app/admin/forgot/pin/email',
    USER_DETAILS: '/app/admin/user',
    COUNTRY_CODE: '/app/admin/list/countryCode',
    STATE_AND_CITY: '/app/admin/list-countries',
    CUSTOMER_LIST: '/app/admin/list/customers',
    UPDATE_PROFILE: '/app/admin/update/details',
    HISTORY_LIST: '/app/admin/appointments',
    UPCOMING_BOOKING_LIST: '/app/admin/upcoming',
    CAN_SERVE_USERS_LIST: '/app/admin/list/can-serve',
    CALENDAR_BOOKING_LIST: '/app/admin/calender/booking/available',
    APPOINTMENT_LIST: '/app/admin/appointment/list',
    BOOKING_STATUS_CHANGE: '/app/admin/update/business/booking-status',
    WAITLIST_STATUS_CHANGE: '/app/admin/update/business/waitlist-status',
    SERVICES_LIST: '/app/admin/services',
    USER_AVAILABILITY_INFO: '/app/admin/check/can-serve',
    SESSION_START: '/app/admin/update/session/start',
    SESSION_END: '/app/admin/update/session/end',
    ADD_BOOKING: '/app/admin/new/booking',
    RESCHEDULE_APPOINTMENT: '/app/admin/update/booking',
    ADD_QUEUE: '/app/admin/add/waitlist',
    BOOKING_PAYMENT_INFO: '/app/admin/payment/appointment',
    QUEUE_PAYMENT_INFO: '/app/admin/payment/queue',
    NOTIFICATION_LIST: '/app/admin/notification',
    UPDATE_NOTIFICATION: '/app/admin/update/notification',
    UPDATE_NOTIFICATION_ALL: '/app/admin/update-all/read-status',
    SERVING_USER_LIST: '/app/admin/list-serving-user',
    DEPARTMENT_LIST: '/app/admin/department/list',
    DIRECT_CHECK_IN: '/app/admin/add/direct-consultation',
    REMOVE_DIRECT_CHECK_IN: '/app/admin/remove/direct-consultation',
    NOTIFY_DELAY: '/app/admin/notify/delay',
    CUSTOMER_DETAILS: '/app/admin/customer/detail',
    CUSTOMER_NOTES: '/app/admin/notes',
    BOOKING_DETAILS: '/app/admin/booking/detail',
    QUEUE_DETAILS: '/app/admin/queue-detail',
    UPDATE_NOTES: '/app/admin/update/notes',
    UPDATE_NOTES_DROPBOX: '/app/admin/update/notes/dropbox',
    UPDATE_NOTES_FROM_DETAIL: '/app/admin/update/customer/notes',
    ADD_NOTES_FROM_DETAIL: '/app/admin/customer/notes',
    REMOVE_NOTES: '/app/admin/remove/customer/notes',
    CANCEL_BOOKING: '/app/admin/update/business/booking-status',
    CANCEL_QUEUE: '/app/admin/update/business/waitlist-status',
    USER_AUTH_INFO: '/app/admin/authentication-info',
    SCHEDULE_NEXT_VISIT: '/app/admin/set/reminder',
    FETCH_PAYMENT_INFO: '/app/admin/pay/offline',
    UPDATE_PAYMENT_INFO: '/app/admin/update/payment/offline',
    AVAILABLE_BOOKING: '/app/admin/booking/available',
    ALL_SLOTS: '/app/admin/slots/list',
    AVAILABLE_QUEUE: '/app/admin/queue-slots',
    ALL_QUEUE_SLOTS: '/app/admin/queue/slots/list',
    CREATE_CUSTOMER: '/app/admin/save/customer',
    UPDATE_VITALS: '/app/admin/appointment/update/vitals',
    DASHBOARD_COUNTS: '/app/admin/upcoming/dashboard',
    AVERAGE_SERVING_TIME_DATA: '/app/admin/average/dashboard',
    AVERAGE_SERVING_COUNT: '/app/admin/average/serving/dashboard',
    DEPARTMENT_VISIT: '/app/admin/dashboard/departments',
    DEVICE_REGISTRATION: '/app/admin/register/device',
    PASSWORD_CHANGE: '/app/admin/update/password',
    EMAIL_UPDATE: '/app/admin/reset/email',
    PROFILE_IMAGE_UPLOAD: '/app/admin/profile/image',
    LOGOUT: '/app/admin/logout',
    REFUND: '/app/admin/update/refund/status',
    UPDATE_BREAK_TIME: '/app/admin/emergency-break',
    UPDATE_AVAILABILITY: '/app/admin/update/availability',
  },

  KEYS: {
    BUSINESS_ID: 'business_id',
    USERNAME: 'userName',
    PASSWORD: 'password',
    ADMIN_ID: 'admin_id',
    USER_ID: 'user_id',
    SERVING_USER_ID: 'servingUser_id',
    AUTHORIZATION: 'Authorization',
    PHONE_NUMBER: 'phoneNumber',
    AUTHENTICATION_PIN: 'authenticationPin',
    STATUS: 'status',
    EMAIL: 'email',
    COUNTRY_CODE: 'countryCode',
    TIME: 'time',
    START_DATE: 'startDate',
    END_DATE: 'endDate',
    BOOKING_ID: 'booking_id',
    QUEUE_ID: 'queue_id',
    WAITLIST_ID: 'waitlist_id',
    CUSTOMER_ID: 'customer_id',
    DURATION: 'duration',
    PAYMENT_TYPE: 'paymentType',
    PAYMENT_REFERENCE_ID: 'paymentReference_id',
    PAYMENT_STATUS: 'paymentStatus',
    SERVICES: 'services',
    EXPECTED_TIME_OF_SERVING: 'expectedTimeOfServing',
    PREFERRED_TIME_FROM: 'preferedTimeFrom',
    PREFERRED_TIME_TO: 'preferedTimeTo',
    GENDER: 'gender',
    READ_STATUS: 'readStatus',
    NOTIFICATION_ID: 'notification_id',
    CONSULTATION_ID: 'consultation_id',
    NOTES: 'notes',
    IMAGE: 'image',
    NOTES_IMAGES: 'notesImages',
    NEXT_SCHEDULE_DATE: 'nextScheduleDate',
    FILTER: 'filter',
    DEVICE_ID: 'device_id',
    DEVICE: 'device',
    TOKEN: 'device_token_id',
    OLD_PASSWORD: 'oldPassword',
    NEW_PASSWORD: 'newPassword',
    CONSULTATION_DATE: 'consultationDate',
    NOTE_ID: 'note_id',
    REFUND_STATUS: 'refundStatus',
    FROM_TIME: 'fromTime',
    TO_TIME: 'toTime',
  },
};
