export default {
  // Spotless
  SPOTLESS_SPLASH_IMAGE: require('../assets/images/SpotlessSplash.png'),
  SPOTLESS_LOGO: require('../assets/images/spotlessLogo.png'),
  INSTA_LOGO: require('../assets/images/al-noor/InstaLogo.png'),
  AL_NOOR_SPLASH_IMAGE: require('../assets/images/al-noor/alNoorSplash.png'),
  AL_NOOR_LOGO: require('../assets/images/al-noor/al-noorLogo.png'),
  FIRST_RESPONSE_SPLASH_SCREEN:require('../assets/images/firstResponse/firstResponseServeSplash.png'),
  FIRST_RESPONSE_LOGO:require('../assets/images/firstResponse/firstResponseServeLogo.png'),
  FIRST_RESPONSE_IMAGE:require('../assets/images/firstResponse/Mask_group.png'),
  ASTER_SPLASH_SCREEN: require('../assets/images/SplashAsterServe.png'),
  ASTER_LOGO: require('../assets/images/asterServeLogo.png'),
  EMPTY_CALENDAR_IMAGE: require('../assets/images/empty-upcoming-data-icon.png'),
  SKILLIKZ_BLUE_TEXT_LOGO_IMAGE: require('../assets/images/skillikzWhiteLogo.png'),
  PRINCE_COURT_SPLASH_SCREEN: require('../assets/images/PrinceCourtSplashScreen.png'),
  PRINCE_COURT_ICON: require('../assets/images/princeCourtImage.png'),
  ADVENTA_SPLASH_SCREEN: require('../assets/images/AdventaSplashScreen.png'),
  IMAGE_PLACEHOLDER: require('../assets/images/placeHolder.jpeg'),
  ADVENTA_ICON: require('../assets/images/AdventaImage.png'),
  WEB_IMAGE: require('../assets/images/wwwGlobeIcon.png'),
  RADIO_BUTTON_ON: require('../assets/images/radioBtnOn.png'),
  RADIO_BUTTON_OFF: require('../assets/images/radioBtnOff.png'),
  BACK_ARROW_IMAGE: require('../assets/images/backArrow.png'),
  EMAIL_UPDATE_IMAGE: require('../assets/images/emailUpdate.png'),
  PASSWORD_UPDATE_IMAGE: require('../assets/images/editPassword.png'),
  LOGOUT_IMAGE: require('../assets/images/logoutIcon.png'),
  EDIT_PERSONAL_INFO_IMAGE: require('../assets/images/editPen.png'),
  PIN_AUTH_IMAGE: require('../assets/images/pinSettings.png'),
  EDIT_PIN_IMAGE: require('../assets/images/editPen.png'),
  WORD_FILE_ICON: require('../assets/images/wordFileIcon.png'),
  PDF_FILE_ICON: require('../assets/images/pdfImages.png'),
  DROP_DOWN_ICON: require('../assets/images/drop-down-arrow-icon.png'),
  CALENDAR_ICON: require('../assets/images/calendar-icon.png'),
  CLOSE_ICON: require('../assets/images/close-templated-icon.png'),
  SEARCH_ICON: require('../assets/images/searchWhiteIcon.png'),
  FILES_ICON: require('../assets/images/filesIcon.png'),
  GALLERY_ICON: require('../assets/images/imageGalleryIcon.png'),
  CAMERA_ICON: require('../assets/images/cameraIcon.png'),
  PHONE_ICON: require('../assets/images/phoneIcon.png'),
  LOCATION_ICON: require('../assets/images/locationIcon.png'),
  PLUS_FILL_ROUND_ICON: require('../assets/images/plusFillRoundIcon.png'),
  PLUS_SQUARE_ICON: require('../assets/images/plus-square-templated-icon.png'),
  CROSS_BUTTON_ICON: require('../assets/images/crossButtonIcon.png'),
  YWAIT_Y_LOGO: require('../assets/images/ywaitYIcon.png'),
  YWAIT_LOGO_:require('../assets/images/app-logo-icon.png'),
  MANAGE_QUEUE_ICON: require('../assets/images/manage-users-icon-templated.png'),
  REPORTS_ICON: require('../assets/images/reports-icon-templated.png'),
  MORNING_ICON: require('../assets/images/morning.png'),
  EVENING_ICON: require('../assets/images/evening.png'),
  PLAY_ICON: require('../assets/images/playIcon.png'),
  STOP_ICON: require('../assets/images/stopIcon.png'),
  EYE_ICON: require('../assets/images/eyeViewIcon.png'),
  PLUS_ICON: require('../assets/images/plus-icon.png'),
  THREE_DOTS_OPTION: require('../assets/images/threeDotsOptionIcon.png'),
  RESCHEDULE_ICON: require('../assets/images/reSchedule.png'),
  GRAY_SEARCH_ICON: require('../assets/images/search-lens-grey-icon.png'),

  CLOCK_CIRCULAR_ICON: require('../assets/images/clock-circular-outline-templated.png'),
  SERVICE_SELECT_ICON: require('../assets/images/service-select-icon.png'),
  STATUS_CHANGE_RADIO_OFF: require('../assets/images/statusChangeRadioOn.png'),
  PLUS_CALENDER_ICON: require('../assets/images/plus-icon.png'),
  MINUS_ICON: require('../assets/images/minusIcon.png'),
  DASHBOARD_PLUS_ICON: require('../assets/images/plus-icon-templated.png'),
  ANNOUNCEMENT_ICON: require('../assets/images/loudspeaker-with-two-sound-waves.png'),
  SAVE_TICK_ICON: require('../assets/images/saveTick.png'),
  PAY_NOW_ICON: require('../assets/images/payNowIcon.png'),
  ALARM_CLOCK_ICON: require('../assets/images/alarmClockIcon.png'),
  VITALS_ICON: require('../assets/images/vitalHeartIcon.png'),
  INFO_ICON: require('../assets/images/infoIcon.png'),
  DASHBOARD_APPOINTMENTS_ICON: require('../assets/images/dashboard_appointment_icon.png'),
  DASHBOARD_NEW_CUSTOMERS_ICON: require('../assets/images/dashboard_customers_icon.png'),
  DASHBOARD_WALK_IN_ICON: require('../assets/images/dashboard_walk_in_icon.png'),
  DASHBOARD_CANCELLED_ICON: require('../assets/images/dashboard_cancelled_icon.png'),
  DASHBOARD_NO_SHOW_ICON: require('../assets/images/nowShowIcon.png'),
  DASHBOARD_SERVING_TIME_ICON: require('../assets/images/averageServingIcon.png'),
  DASHBOARD_UP_ARROW_ICON: require('../assets/images/up-arrow-fill.png'),
  WARNING_ICON: require('../assets/images/cautionIcon.png'),
  SKILLIKZ_Q_LOGO: require('../assets/images/skillikzQWhite.png'),
  SKILLIKZ_Q_TEXT: require('../assets/images/skillikzQText.png'),
  SKILLIKZ_Q_PINK: require('../assets/images/SkillikzQPink.png'),

  //Lottie
  MALE_ANIMATION_ICON: require('../assets/animations/maleAnimIcon.json'),
  FEMALE_ANIMATION_ICON: require('../assets/animations/femaleAnimIcon.json'),
  UNISEX_ANIMATION_ICON: require('../assets/animations/unisexAnimIcon.json'),
  OTHER_ANIMATION_ICON: require('../assets/animations/otherAnimIcon.json'),
  SUCCESS_ANIMATION: require('../assets/animations/successfullAnimation.json'),
  FAILED_ANIMATION: require('../assets/animations/failedAnimation.json'),
  LOTTIE_DATE_CALENDAR_ANIMATION: require('../assets/animations/dateCalendarAnimation.json'),
  LOTTIE_SEARCH_NO_RESULT: require('../assets/animations/searchNoResult.json'),
  RED_NOTIFICATION_ICON: require('../assets/animations/notificationRedAnimation.json'),
  GRAY_NOTIFICATION_ICON: require('../assets/animations/notificationGreyAnimation.json'),
  EMPTY_NOTIFICATION_LIST: require('../assets/animations/noNotificationAnimation.json'),
  EMPTY_CHAIR_ANIMATION_ICON: require('../assets/animations/emptyChair.json'),
  EMPTY_CHAIR_ANIMATION: require('../assets/animations/servingUserNoSearchAnimation.json'),
  WHITE_NOTIFICATION_ANIMATION: require('../assets/animations/notificationWhiteAnimation.json'),
  EMPTY_MANAGE_QUEUE_ANIMATION: require('../assets/animations/emptyChair.json'),
  SLOT_FULL_ANIMATION: require('../assets/animations/slotFullAnimation.json'),
  BUSINESS_CLOSED_ANIMATION: require('../assets/animations/businessClosedAnimation.json'),

  //GIF
  SKILLIKZ_LOADER: require('../assets/animations/skillikz_serve_loader.gif'),
  SKILLIKZ_SPLASH_ANIMATION: require('../assets/animations/Skillikz_Queue_Splash_Blue.gif'),

  // RTL
  CHANGE_LANGUAGE: require('../assets/images/language.png'),
};
